version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cle_broker
    volumes:
      - cle_broker_pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/cle_broker}
    ports:
      - '3000:3000'
    command: ['node', 'dist/server.js']
volumes:
  cle_broker_pgdata:
